LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := app
LOCAL_LDFLAGS := -Wl,--build-id
LOCAL_SRC_FILES := \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\arm64-v8a\libopencv_calib3d.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\arm64-v8a\libopencv_core.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\arm64-v8a\libopencv_features2d.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\arm64-v8a\libopencv_flann.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\arm64-v8a\libopencv_highgui.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\arm64-v8a\libopencv_imgcodecs.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\arm64-v8a\libopencv_imgproc.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\arm64-v8a\libopencv_java3.so \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\arm64-v8a\libopencv_ml.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\arm64-v8a\libopencv_objdetect.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\arm64-v8a\libopencv_photo.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\arm64-v8a\libopencv_shape.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\arm64-v8a\libopencv_stitching.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\arm64-v8a\libopencv_superres.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\arm64-v8a\libopencv_video.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\arm64-v8a\libopencv_videoio.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\arm64-v8a\libopencv_videostab.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi\libopencv_calib3d.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi\libopencv_core.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi\libopencv_features2d.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi\libopencv_flann.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi\libopencv_highgui.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi\libopencv_imgcodecs.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi\libopencv_imgproc.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi\libopencv_java3.so \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi\libopencv_ml.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi\libopencv_objdetect.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi\libopencv_photo.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi\libopencv_shape.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi\libopencv_stitching.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi\libopencv_superres.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi\libopencv_video.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi\libopencv_videoio.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi\libopencv_videostab.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi-v7a\libopencv_calib3d.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi-v7a\libopencv_core.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi-v7a\libopencv_features2d.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi-v7a\libopencv_flann.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi-v7a\libopencv_highgui.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi-v7a\libopencv_imgcodecs.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi-v7a\libopencv_imgproc.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi-v7a\libopencv_java3.so \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi-v7a\libopencv_ml.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi-v7a\libopencv_objdetect.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi-v7a\libopencv_photo.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi-v7a\libopencv_shape.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi-v7a\libopencv_stitching.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi-v7a\libopencv_superres.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi-v7a\libopencv_ts.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi-v7a\libopencv_video.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi-v7a\libopencv_videoio.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\armeabi-v7a\libopencv_videostab.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips\libopencv_calib3d.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips\libopencv_core.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips\libopencv_features2d.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips\libopencv_flann.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips\libopencv_highgui.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips\libopencv_imgcodecs.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips\libopencv_imgproc.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips\libopencv_java3.so \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips\libopencv_ml.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips\libopencv_objdetect.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips\libopencv_photo.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips\libopencv_shape.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips\libopencv_stitching.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips\libopencv_superres.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips\libopencv_video.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips\libopencv_videoio.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips\libopencv_videostab.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips64\libopencv_calib3d.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips64\libopencv_core.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips64\libopencv_features2d.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips64\libopencv_flann.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips64\libopencv_highgui.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips64\libopencv_imgcodecs.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips64\libopencv_imgproc.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips64\libopencv_java3.so \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips64\libopencv_ml.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips64\libopencv_objdetect.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips64\libopencv_photo.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips64\libopencv_shape.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips64\libopencv_stitching.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips64\libopencv_superres.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips64\libopencv_video.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips64\libopencv_videoio.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\mips64\libopencv_videostab.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86\libopencv_calib3d.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86\libopencv_core.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86\libopencv_features2d.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86\libopencv_flann.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86\libopencv_highgui.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86\libopencv_imgcodecs.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86\libopencv_imgproc.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86\libopencv_java3.so \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86\libopencv_ml.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86\libopencv_objdetect.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86\libopencv_photo.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86\libopencv_shape.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86\libopencv_stitching.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86\libopencv_superres.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86\libopencv_video.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86\libopencv_videoio.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86\libopencv_videostab.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86_64\libopencv_calib3d.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86_64\libopencv_core.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86_64\libopencv_features2d.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86_64\libopencv_flann.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86_64\libopencv_highgui.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86_64\libopencv_imgcodecs.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86_64\libopencv_imgproc.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86_64\libopencv_java3.so \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86_64\libopencv_ml.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86_64\libopencv_objdetect.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86_64\libopencv_photo.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86_64\libopencv_shape.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86_64\libopencv_stitching.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86_64\libopencv_superres.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86_64\libopencv_video.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86_64\libopencv_videoio.a \
	C:\Users\User\Desktop\Panorama\app\src\main\jni\x86_64\libopencv_videostab.a \

LOCAL_C_INCLUDES += C:\Users\User\Desktop\Panorama\app\src\main\jni
LOCAL_C_INCLUDES += C:\Users\User\Desktop\Panorama\app\src\debug\jni

include $(BUILD_SHARED_LIBRARY)
